/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Venda.Telas;

import br.com.Produto.Model.ProdutoBLL;
import br.com.Venda.DAL.ModuloConexao;
import br.com.Venda.Model.vendaBLL;
import br.com.Venda.Model.vendaDTO;
import static br.com.Venda.Telas.TelaVenda.VendNome;
import static br.com.Venda.Telas.TelaVenda.VendProduto;
import static br.com.Venda.Telas.TelaVenda.VendQtd;
import static br.com.Venda.Telas.TelaVenda.VendTable3;
import static br.com.Venda.Telas.TelaVenda.VendAdd;
import static br.com.Venda.Telas.TelaVenda.ValorFinal;
import static br.com.Venda.Telas.TelaVenda.VendValorItem;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import javazoom.jl.player.*;
import javazoom.jl.decoder.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.player.Player;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author T69779848134
 */
public class TPagamento extends javax.swing.JFrame {

    ModuloConexao conexao = new ModuloConexao();
    PreparedStatement pst;
    ResultSet rs;

    private void Venda() {
        String sql = "insert into venda (nome, descricao, qtdp, valor_item, valor_sub_total, valor_total, forma_pg) \n"
                + "select C.nome, C.descricao, C.qtdp, C.valor_item, C.valor_sub_total, C.valor_total,\n"
                + "T.forma_pg from carrinho C , teste T where C.id_c = T.id_t;";
        conexao.conector();
        try {
            PreparedStatement pst = conexao.conn.prepareStatement(sql);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " Erro! " + e.getMessage());
        }
    }

    // metodo para "getar" pegar o que vao para o banco
    private void MostraTotal() {
        conexao.conector();
        try {
            conexao.executaSQL("select valor_total from carrinho order by nome desc;");  // string para habilitar os get's
            conexao.rs.last();

            TxtvalorFinal.setText(conexao.rs.getString("valor_total"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

//    public void som() {
//        try {
//            File file = new File("C:\\Users\\t69779848134\\Documents\\NetBeansProjects\\ProjetoVenda-5.1-MySQL\\src\\br\\com\\Audio\\Cr.mp3");
//            FileInputStream fis = new FileInputStream(file);
//            BufferedInputStream bu = new BufferedInputStream(fis);
//
//            try {
//                Player player = new Player(bu);
//                player.play();
//            } catch (Exception e) {
//                System.out.println("Erro ao tentar reproduzir o som" + e.getMessage());
//            }
//        } catch (Exception e) {
//            System.out.println("Erro ao tentar reproduzir o som" + e.getMessage());
//        }
//    }

    private void excluir() {
        String sql = "truncate teste ;";
        try {
            pst = conexao.conn.prepareStatement(sql);
            pst.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo deu Errado" + e.getMessage());

        }
    }
     private void excluir2() {
        String sql = "truncate carrinho ;";
        try {
            pst = conexao.conn.prepareStatement(sql);
            pst.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo deu Errado" + e.getMessage());

        }
    }

    public void pesquisaCarrinho(String sql) {
        conexao.conector();
        try {
            pst = conexao.conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //  a linha abaixo usa a biblioteca rs2xml.jar                           
            VendTable3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    vendaBLL bll = new vendaBLL();
    ProdutoBLL bl2 = new ProdutoBLL();
    vendaDTO dto = new vendaDTO();

    /**
     * Creates new form TPagamento
     */
    public TPagamento() {
        initComponents();
        MostraTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CboCont = new javax.swing.JComboBox<>();
        BtnFinal = new javax.swing.JButton();
        TxtvalorFinal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Por favor - Escolha a Forma de Pagamento");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CboCont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CboCont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Débito", "Crédito", "Fiado" }));
        CboCont.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnFinal.setText("Finalizar");
        BtnFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalActionPerformed(evt);
            }
        });

        TxtvalorFinal.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        TxtvalorFinal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.darkShadow"));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtvalorFinal)
                            .addComponent(CboCont, 0, 233, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(BtnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(CboCont, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtvalorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalActionPerformed
        String cbo = CboCont.getSelectedItem().toString();
        bll.SalvaCarrinho(cbo);
        Venda();
        VendNome.setEnabled(true);
        VendTable3.setVisible(false);
        VendAdd.setEnabled(false);
        excluir();// TODO add your handling code here:
        excluir2();
        this.dispose();
//        som();


    }//GEN-LAST:event_BtnFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinal;
    public static javax.swing.JComboBox<String> CboCont;
    private javax.swing.JTextField TxtvalorFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
